In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
sb.set()

In [7]:
data = pd.read_csv('survey lung cancer.csv')
data.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

In [10]:
df = data.copy()
df['GENDER'] = df['GENDER'].map({'M': 1,'F':0})
df['LUNG_CANCER'] = df['LUNG_CANCER'].map({'YES':1,'NO':0})

In [11]:
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        1               2        2              1   
1       1   74        2               1        1              1   
2       0   59        1               1        1              2   
3       1   63        2               2        2              1   
4       0   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0

In [21]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
scx = StandardScaler()
x = scx.fit_transform(x)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [22]:
x_train

array([[-1.04978132, -1.42407363,  0.88083033, ...,  0.74873631,
         1.06350105, -1.12047956],
       [ 0.95257934,  1.13783759,  0.88083033, ...,  0.74873631,
         1.06350105,  0.892475  ],
       [ 0.95257934, -0.44810745,  0.88083033, ...,  0.74873631,
        -0.94029056, -1.12047956],
       ...,
       [-1.04978132, -1.42407363,  0.88083033, ...,  0.74873631,
         1.06350105, -1.12047956],
       [-1.04978132,  0.16187141,  0.88083033, ..., -1.33558369,
         1.06350105,  0.892475  ],
       [ 0.95257934, -0.81409477, -1.13529242, ..., -1.33558369,
        -0.94029056, -1.12047956]])

### **Logistic Regression**

In [23]:
log = LogisticRegression()
log.fit(x_train,y_train)
y_pred  = log.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [34]:
log.coef_

array([[ 0.0850526 , -0.11855493,  0.54363238,  0.49596798,  0.33976425,
         0.6688882 ,  1.20796174,  1.11181656,  0.86152845,  0.29647591,
         0.77221061,  0.79752674, -0.09807634,  0.84696987,  0.21385118]])

In [35]:
log.intercept_

array([3.9614879])

In [40]:
find = pd.DataFrame()
find['Factors'] = df.iloc[:,:-1].columns.values
find['Coefficients'] = np.transpose(log.coef_)
find['Odds Ratio'] = np.transpose(np.exp(log.coef_))
find.sort_values('Odds Ratio',ascending = False)

Factors  Coefficients  Odds Ratio
6         CHRONIC DISEASE      1.207962    3.346656
7                FATIGUE       1.111817    3.039875
8                ALLERGY       0.861528    2.366775
13  SWALLOWING DIFFICULTY      0.846970    2.332568
11               COUGHING      0.797527    2.220043
10      ALCOHOL CONSUMING      0.772211    2.164546
5           PEER_PRESSURE      0.668888    1.952066
2                 SMOKING      0.543632    1.722251
3          YELLOW_FINGERS      0.495968    1.642087
4                 ANXIETY      0.339764    1.404616
9                WHEEZING      0.296476    1.345110
14             CHEST PAIN      0.213851    1.238438
0                  GENDER      0.085053    1.088774
12    SHORTNESS OF BREATH     -0.098076    0.906580
1                     AGE     -0.118555    0.888203

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score
res = confusion_matrix(y_pred,y_test)
res

array([[ 5,  1],
       [ 5, 51]])

In [31]:
res1 = accuracy_score(y_pred,y_test)
res1

0.9032258064516129

### **K Nearest Neighbors**

In [58]:
klass = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski',p = 15)
klass.fit(x_train,y_train)
y_pred2 = klass.predict(x_test)
y_pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
res2 = confusion_matrix(y_pred2,y_test)
res2

array([[ 3,  1],
       [ 7, 51]])

In [60]:
res3 = accuracy_score(y_pred2,y_test)
res3

0.8709677419354839